Repository RE-V-UP/vvv, pull requests merged in 2024-04, with the labels that each got.

#56 Feat(#2) : 마이페이지 - 팔로잉/팔로워 데이터 조회 작업 및 유저 팔로우/언팔로우 기능 작업, 탭메뉴 구현
  next.config.mjs
  src/components/main/MainBanner.tsx
  src/components/mypage/FollowList.tsx
  src/components/mypage/Modal.tsx
  src/components/mypage/MyInfo.tsx
  src/components/mypage/TabMenu.tsx
  src/shared/mypage/api.ts
Labels: documentation, enhancement

#66 fix(#64) : 커뮤니티 등록, 조회, 수정, 삭제에 필요한 쿼리 키, 함수 정리
  next.config.mjs
  src/app/(nonAuth)/community/[id]/page.tsx
  src/app/UserProvider.tsx
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/LikeButton.tsx
  src/components/communityDetail/communityDetailEdit.tsx
  src/components/communityDetail/communityDetailRead.tsx
  src/components/main/MainBanner.tsx
  src/query/communityDetail/communityMutation.ts
  src/query/communityDetail/communityQueryKey.ts
  src/shared/communitydetail/detailApi.ts
  src/shared/join/joinApi.ts
  src/types/communityDetail/detailTypes.ts
  src/types/supabase.ts
  src/util/Modal.tsx
  tsconfig.json
Labels: documentation, enhancement

#69 Feat(#52),fix(#68) : 커뮤니티 상세 페이지 - 등록 함수 세팅 및 pr리뷰 요청 수정 - 빠진 return 추가
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/query/communityDetail/communityMutation.ts
  src/shared/communitydetail/detailApi.ts
  src/types/communityDetail/detailTypes.ts
Labels: documentation, enhancement

#70 Feat(#5) : 뮤직플레이어 구현중
  package.json
  src/app/(nonAuth)/community/page.tsx
  src/app/(nonAuth)/search/page.tsx
  src/app/page.tsx
  src/components/player/CurrentMusicPlayer.tsx
  src/components/player/MusicPlayer.tsx
  src/components/search/MusicSearchModal.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchedCommunityData.tsx
  src/components/search/SearchedMusicData.tsx
  src/shared/community/api.ts
  src/shared/musicPlayer/api.ts
  src/shared/search/api.ts
  src/types/types.ts
  yarn.lock
Labels: enhancement

#73 Feat(#52) : 커뮤니티 글 등록 세팅중
  src/app/(auth)/communitycreate/page.tsx
  src/app/(nonAuth)/community/[id]/page.tsx
  src/app/(nonAuth)/community/page.tsx
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/search/MusicSearch.tsx
  src/components/search/MusicSearchModal.tsx
  src/query/communityDetail/communityMutation.ts
  src/shared/store/communityDetailStore.ts
Labels: documentation, enhancement

#82 Feat(#1) 마이플레이리스트 등록 완료
  src/app/(nonAuth)/community/page.tsx
  src/app/(nonAuth)/search/page.tsx
  src/components/player/CurrentMusicPlayer.tsx
  src/components/search/SearchForm.tsx
  src/shared/musicPlayer/api.ts
  src/shared/store/searchStore.ts
Labels: enhancement

#85 Feat(#81) : 커뮤니티, 플레이리스트 페이지네이션
  src/app/(nonAuth)/community/page.tsx
  src/app/(nonAuth)/search/page.tsx
  src/app/page.tsx
  src/components/player/CurrentMusicList.tsx
  src/components/player/MusicPlayer.tsx
  src/components/player/Pagination .tsx
  src/components/search/MusicSearchModal.tsx
  src/components/search/SearchedCommunityData.tsx
  src/components/search/SearchedMusicData.tsx
  src/types/community/type.ts
  src/types/musicPlayer/types.ts
  src/types/supabase.ts
Labels: enhancement

#92 Fix(#91,#53) : 글 등록 로직 및 글 수정 로직 수정
  src/app/(nonAuth)/community/page.tsx
  src/app/UserProvider.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/logout/LogOutButton.tsx
  src/query/communityDetail/communityMutation.ts
  src/query/communityDetail/communityQueryKey.ts
  src/shared/communitydetail/detailApi.ts
  src/shared/store/communityDetailStore.ts
  src/types/communityDetail/detailTypes.ts
Labels: documentation, enhancement

#94 Feat(#55) : 커뮤니티 상세 페이지 - 좋아요 기능 완성
  public/images/likeFullHeart.svg
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/communityDetail/LikeButton.tsx
  src/shared/communitydetail/detailApi.ts
  src/types/communityDetail/detailTypes.ts
Labels: documentation, enhancement

#96 Feat(#93) : 커뮤니티 상세 페이지 - 음악 검색 후 검색한 음악 조회 세팅
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/search/MusicSearchModal.tsx
Labels: documentation, enhancement

#103 Feat(#101) : 유저 플레이어 - 노래 선택/전체 재생(추가) 기능 코드 수정
  src/components/userpage/LikeBoardList.tsx
  src/components/userpage/LockContents.tsx
  src/components/userpage/UserPlaylist.tsx
  src/components/userpage/WriteList.tsx
Labels: documentation, enhancement

#105 Feat(#97,#104) : 현재 플레이리스트에 노래 선택/전체 추가 기능
  src/components/mypage/LikeBoardList.tsx
  src/components/mypage/MyInfo.tsx
  src/components/mypage/MyPlaylist.tsx
  src/components/mypage/WriteList.tsx
  src/shared/mypage/api.ts
Labels: documentation, enhancement

#110 Feat(#108) : 댓글 수정 input창으로 입력된 값으로 변경 테스트
  .github/ISSUE_TEMPLATE/basic-issue-template.md
  src/app/(auth)/comment/page.tsx
  src/components/Header.tsx
  src/components/comment/CommentForm.tsx
  src/components/comment/CommentsList.tsx
  src/components/communityDetail/communityDetailRead.tsx
  src/components/main/TopLikedBoard.tsx
  src/shared/comment/commentApi.ts
  src/util/comment/util.ts
  src/util/util.ts
Labels: bug, documentation, enhancement

#111 Fix(#95) : 로그인 - DB 테이블 providerUserInfo에 일반 이메일 유저도 들어가던 문제 해결
  src/app/(nonAuth)/join/page.tsx
  src/app/UserProvider.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/components/socialLogin/page.tsx
  src/shared/join/joinApi.ts
  src/shared/store.ts
Labels: bug, documentation, enhancement

#120 Feat(#106,#107,#117,#118) : 마이/유저 플레이리스트 페이지네이션 및 노래시간 데이터 추가 작업 / Fix(#116,#119) : 팔로잉 업데이트 및 플레이리스트 전체 재생(추가) 에러 처리
  src/components/mypage/LikeBoardList.tsx
  src/components/mypage/MyPlaylist.tsx
  src/components/mypage/WriteList.tsx
  src/components/userpage/LikeBoardList.tsx
  src/components/userpage/UserInfo.tsx
  src/components/userpage/UserPlaylist.tsx
  src/components/userpage/WriteList.tsx
  src/shared/mypage/api.ts
  src/types/mypage/types.ts
Labels: bug, documentation, enhancement

#127 Fix(#122) : 로그인 - useInfo의 uid 대신 useSession의 uid 적용 및 소셜로그인 환경 제거
  src/app/(nonAuth)/login/page.tsx
  src/app/UserProvider.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/page.tsx
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/communityDetail/LikeButton.tsx
  src/components/findpassword/FindPassword.tsx
  src/components/socialLogin/page.tsx
  src/shared/communitydetail/detailApi.ts
  src/shared/join/joinApi.ts
  src/shared/login/loginApi.ts
  src/types/supabase.ts
  src/util/util.ts
Labels: documentation

#136 Feat(#130) : 메인페이지 컴포넌트 - 로그인 유저 정보 useSession으로 변경
  src/components/main/GenreMusicItem.tsx
  src/components/main/GenreMusicList.tsx
  src/components/main/MainBanner.tsx
  tsconfig.json
Labels: documentation, enhancement

#141 Chore(#137) : 필요없는 css 설정 제거
  src/app/globals.css
  src/app/layout.tsx
  src/components/comment/CommentsList.tsx
  src/util/font.ts
  tailwind.config.ts
Labels: documentation, enhancement

#142 Feat(#138,#139) : 마이페이지/유저페이지 - 로그인 정보 useSession으로 변경 / Fix(#140) : 메인 음악추천 컴포넌트 로그인 체크 로직 수정
  src/components/main/GenreMusicItem.tsx
  src/components/mypage/FollowList.tsx
  src/components/mypage/LikeBoardList.tsx
  src/components/mypage/MyInfo.tsx
  src/components/mypage/MyPlaylist.tsx
  src/components/mypage/WriteList.tsx
  src/components/userpage/LikeBoardList.tsx
  src/components/userpage/UserInfo.tsx
  src/components/userpage/UserPlaylist.tsx
  src/components/userpage/WriteList.tsx
Labels: bug, documentation, enhancement

#147 Feat(#146) : 댓글 페이지 - 로그인 정보 useSession으로 변경
  src/components/comment/CommentForm.tsx
  src/components/comment/CommentsList.tsx
Labels: documentation, enhancement

#151 Feat(#150): 로그인 - 세션 날아감 현상 임시 대처
  src/app/UserProvider.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/search/ModalMusicData.tsx
  src/components/search/MusicSearchModal.tsx
  src/query/communityDetail/communityMutation.ts
  src/shared/communitydetail/detailApi.ts
  src/shared/join/joinApi.ts
  src/shared/store/communityDetailStore.ts
Labels: bug, documentation, enhancement

#153 Feat(#113) : Header icon svg 파일로 추출 후 추가
  public/images/backButton.svg
  public/images/commuIcon.svg
  public/images/mypageIcon.svg
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/logout/LogOutButton.tsx
  tailwind.config.ts
Labels: documentation, enhancement

#155 Feat(#152) : 세션 날아감 현상 대처 및 빌드 오류 해결
  src/app/UserProvider.tsx
  src/app/UserReSessionProvider.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/search/MusicSearchModal.tsx
Labels: bug, documentation, enhancement

#156 Feat(#135) : 등록 페이지 함수, 이미지 디버깅 완료
  .prettierrc
  public/images/defaultUserImg.png
  public/images/plz-music.png
  src/app/(nonAuth)/join/page.tsx
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/query/communityDetail/communityMutation.ts
  src/shared/communitydetail/detailApi.ts
Labels: documentation, enhancement

#161 Feat(#154,#158) : prettier-plugin-tailwindcss 설정 및 useSession 타입 설정, Style(#149, #160) : 음악추천 컨텐츠 및 전체 레이아웃 ui 작업
  .gitignore
  next-env.d.ts
  next.config.mjs
  next.d.ts
  src/app/(auth)/layout.tsx
  src/app/(nonAuth)/layout.tsx
  src/app/(nonAuth)/main/main.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Header.tsx
  src/components/common/Container.tsx
  src/components/main/GenreMusicItem.tsx
  tsconfig.json
Labels: documentation, enhancement, style

#165 Feat(#164) : 커뮤니티 상세 페이지 - useQuery, mutation, queryKey 분리
  src/app/(nonAuth)/login/page.tsx
  src/app/globals.css
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/login/Login.tsx
  src/components/mypage/MyInfo.tsx
  src/query/communityDetail/communityQueryKey.ts
  src/query/communityDetail/mutation.ts
  src/query/communityDetail/queryKey.ts
  src/shared/main/api.ts
  src/shared/search/api.ts
  src/types/communityDetail/detailTypes.ts
Labels: documentation, enhancement

#169 Style(#149) : 음악 추천 컨텐츠 영역 ui 작업
  public/images/next.svg
  public/images/plus.svg
  public/images/prev.svg
  src/app/globals.css
  src/components/common/Container.tsx
  src/components/main/GenreMusicItem.tsx
  src/components/main/GenreMusicList.tsx
  src/components/main/RandomMusicList.tsx
  src/components/main/RecommendationMusicList.tsx
  src/components/main/SlideButton.tsx
  src/components/mypage/MyPlaylist.tsx
Labels: style

#173 Style(#170) : 메인 배너 슬라이드 ui 작업 / Feat(#172) : 일반 배너로 변경 작업
  src/components/main/GenreMusicItem.tsx
  src/components/main/MainBanner.tsx
Labels: documentation, style

#179 Style(#174, #178) : 메인페이지/메인페이지 컴포넌트 여백 분기, 인기 게시글 컴포넌트 ui 작업
  public/images/heart-rounded-gray.svg
  public/images/message-text-square-02-gray.svg
  src/components/Footer.tsx
  src/components/common/Container.tsx
  src/components/main/MainBanner.tsx
  src/components/main/RandomMusicList.tsx
  src/components/main/RecommendationMusicList.tsx
  src/components/main/SectionTitle.tsx
  src/components/main/TopLikedBoard.tsx
Labels: style

#181 Style/player custom
  public/images/musicList.svg
  public/images/musicLyricsButton.svg
  public/images/musicShuffle.svg
  public/images/musicShuffleOff.svg
  public/images/musicThumbnail.svg
  public/images/myPlayListButton.svg
  public/images/playerBar.svg
  public/images/playerNextButton.svg
  public/images/playerPauseButton.svg
  public/images/playerPlayButton.svg
  public/images/playerPreviousButton.svg
  src/components/player/AudioCss.css
  src/components/player/CurrentMusicList.tsx
  src/components/player/MusicPlayer.tsx
  src/components/player/Player.tsx
  src/components/player/playerIcons/FaForward.tsx
  src/components/player/playerIcons/MyLoopIcon.tsx
  src/components/player/playerIcons/MyLoopOffIcon.tsx
  src/components/player/playerIcons/MyNextIcon.tsx
  src/components/player/playerIcons/MyPauseIcon.tsx
  src/components/player/playerIcons/MyPlayIcon.tsx
  src/components/player/playerIcons/MyPreviousIcon.tsx
  src/components/player/playerIcons/ProgressContainer.tsx
  src/query/community/communityQueryKey.ts
  src/query/musicPlayer/musicPlayerQueryKey.ts
  src/types/musicPlayer/types.ts
Labels: style

#186 Fix(#182) : 유저 페이지 노래 전체 담기 에러 처리
  src/components/userpage/UserPlaylist.tsx
  src/shared/main/api.ts
Labels: bug

#187 Style(#184) : 헤더/푸터 디자인 작업 (+로고통일)
  public/images/Property 1=chevron-left.svg
  public/images/Property 1=message-chat-circle.svg
  public/images/Property 1=search-sm.png
  public/images/Property 1=user-01.svg
  public/images/backButton.svg
  public/images/commuIcon.svg
  public/images/mypageIcon.svg
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/search/SearchForm.tsx
Labels: style

#189 Style(#60, #175, #176, #177),Feat(#188) : 로그인 css, 커뮤니티 상세 페이지- 아바타 클릭 시 해당 유저의 페이지로 이동, 아바타에 마우스 오버 시 툴팁 안내
  package.json
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/login/Login.tsx
  src/components/login/buttonCss.ts
  src/components/login/loginCss.ts
  src/components/socialLogin/page.tsx
  src/shared/communitydetail/detailApi.ts
  src/shared/join/joinApi.ts
  src/types/communityDetail/detailTypes.ts
  tailwind.config.ts
  yarn.lock
Labels: documentation, enhancement

#194 Style(#193) : 댓글 페이지 디자인 작업 마무리
  public/images/Frame 532.svg
  public/images/Icon.svg
  public/images/Property 1=heart-rounded.svg
  public/images/heart-rounded.svg
  public/images/pencil-01.svg
  src/components/comment/CommentForm.tsx
  src/components/comment/CommentsList.tsx
  src/components/search/SearchForm.tsx
Labels: style

#195 Style(#185, #192) : 마이페이지/유저페이지 프로필 영역 ui 작업 및 버튼 컴포넌트 분리
  public/images/chevron-right.svg
  public/images/pencil-line.svg
  src/components/mypage/ButtonPrimary.tsx
  src/components/mypage/ButtonSecondary.tsx
  src/components/mypage/FollowList.tsx
  src/components/mypage/Modal.tsx
  src/components/mypage/MyInfo.tsx
  src/components/mypage/TabMenu.tsx
  src/components/userpage/UserInfo.tsx
  src/types/mypage/types.ts
Labels: style

#200 Fix(#190) : 퍼스널 뮤직 진단 결과 삽입 로직 수정
  package.json
  public/images/Businessman.svg
  src/app/(auth)/personal-music/page.tsx
  src/app/page.tsx
  src/components/comment/CommentForm.tsx
  src/components/comment/CommentsList.tsx
  src/components/comments/CommentForm.tsx
  src/components/comments/CommentsList.tsx
  src/components/common/Container.tsx
  src/components/personal/GenderPage.tsx
  src/components/personal/MBTIPage.tsx
  src/components/personal/PersonalModal.tsx
  src/components/personal/PersonalModalDetail.tsx
  src/components/personal/PersonalRecommend.tsx
  src/components/personal/PersonalSubTest.tsx
  src/components/personal/PersonalTestResult.tsx
  src/components/personal/ResultChart.tsx
  src/components/personal/ResultPage.tsx
  src/query/personal/personalMutation.ts
  src/query/personal/personalQueryKey.ts
  src/shared/comments/commentsApi.ts
  src/shared/community/api.ts
  src/shared/personal/personalApi.ts
  src/shared/store/personalStore.ts
  src/types/comments/type.ts
  src/types/main/types.ts
  src/types/personal/type.ts
  src/types/supabase.ts
  src/util/Modal.tsx
  src/util/personal/util.ts
  yarn.lock
Labels: bug, documentation, enhancement, style

#202 Style(#196,#197) : 마이/유저 플레이리스트 ui 작업
  src/components/mypage/MyInfo.tsx
  src/components/mypage/MyPlaylist.tsx
  src/components/userpage/UserPlaylist.tsx
Labels: style

#204 Style/현재플레이리스트, 노래검색결과페이지 UI완료
  public/images/nextPageButton.svg
  public/images/prevPageButton.svg
  src/app/(nonAuth)/search/page.tsx
  src/app/globals.css
  src/components/mypage/CheckboxItem.tsx
  src/components/player/AudioCss.css
  src/components/player/CurrentMusicList.tsx
  src/components/player/MusicPlayer.tsx
  src/components/player/Pl.tsx
  src/components/player/Player.tsx
  src/components/player/playerIcons/MyPlayIcon.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchedCommunityData.tsx
  src/components/search/SearchedMusicData.tsx
  src/shared/search/api.ts
  src/shared/store/playerStore.ts
  src/util/Pagination .tsx
Labels: style

#208 Style(#201) : 커뮤니티 상세 페이지 CSS - 조회, 로그인 css - 비밀번호 찾기
  public/images/close-button.svg
  public/images/goback.svg
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/LikeButton.tsx
  src/components/communityDetail/communityDetailEdit.tsx
  src/components/communityDetail/detailCss.ts
  src/components/login/Login.tsx
  src/components/login/loginCss.ts
  src/components/socialLogin/page.tsx
  src/util/Modal.tsx
Labels: documentation, style

#213 Style : 커뮤니티 상세 페이지 - 조회 css
  public/images/community-detail-Image/add-current-music.svg
  public/images/community-detail-Image/detail-delete.svg
  public/images/community-detail-Image/detail-edit.svg
  src/components/communityDetail/CommunityContents.tsx
Labels: documentation, style

#219 Fix(#217) : 팔로잉 리스트 취소 에러 문제 처리를 위한 팔로잉/팔로워 컴포넌트 분리
  src/components/mypage/FollowerList.tsx
  src/components/mypage/FollowingList.tsx
  src/components/mypage/MyInfo.tsx
  src/shared/mypage/api.ts
Labels: bug, documentation, enhancement

#222 Fix : MBTI 코드변경 수정
  public/images/logout.svg
  src/components/Header.tsx
  src/components/logout/LogOutButton.tsx
  src/components/mypage/PreviousButton.tsx
  src/components/personal/GenderPage.tsx
  src/components/personal/PersonalModalDetail.tsx
  src/components/personal/PersonalRecommend.tsx
  src/components/personal/PersonalSubTest.tsx
  src/components/personal/PersonalTestResult.tsx
  src/components/personal/ResultChart.tsx
  src/components/search/SearchForm.tsx
  src/shared/personal/personalApi.ts
  src/types/personal/type.ts
Labels: documentation, style

#223 Style(#214) : 커뮤니티 상세 페이지 css - 등록(음악 검색 등록)
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/communityDetail/LikeButton.tsx
  src/components/search/MusicSearchModal.tsx
Labels: documentation, style

#226 Style(#205) : 커뮤니티 리스트 UI
  src/app/(nonAuth)/community/page.tsx
  src/components/communityList/CommunityListData.tsx
  src/components/communityList/CommunityListSort.tsx
  src/components/search/MusicSearchModal.tsx
Labels: style

#228 Fix/layout
  src/app/(auth)/layout.tsx
  src/app/(nonAuth)/layout.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/player/Player.tsx
Labels: bug

#234 Style(#233) : 로그인 css - 로그인 인풋 placeholeder 컬러 복원
  src/components/communityDetail/detailCss.ts
  src/components/login/Login.tsx
  src/components/login/loginCss.ts
  src/shared/join/joinApi.ts
  src/util/Modal.tsx
Labels: documentation, style

#237 Fix(#236) : 팔로우 리스트 - 팔로우 버튼 나오지 않는 문제 처리 및 취소 버튼 추가
  src/components/mypage/FollowList.tsx
  src/components/mypage/FollowerList.tsx
  src/components/mypage/MyInfo.tsx
Labels: bug, documentation

#238 Feat(#235) : 커뮤니티 상세 페이지 - 등록, 음악 검색 등록 유효성 추가
  src/app/(nonAuth)/join/page.tsx
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/findpassword/FindPassword.tsx
  src/components/login/Login.tsx
  src/components/search/MusicSearchModal.tsx
  src/query/communityDetail/mutation.ts
Labels: documentation

#242 Style(#233) : 로그인 css - 로그인 인풋 값 placeholeder 컬러 복원
  src/app/(auth)/new-password/page.tsx
  src/app/(auth)/signout/page.tsx
  src/app/(nonAuth)/community/[id]/page.tsx
  src/app/(nonAuth)/join/page.tsx
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/join/Join.tsx
  src/components/login/Login.tsx
  src/components/login/loginCss.ts
Labels: documentation, style

#245 Fix(#229) : 플레이어 상태 변경시 재생상태 유지 수정 완료
  public/images/musicThumbnail.svg
  src/components/communityList/CommunityListSort.tsx
  src/components/player/AudioCss.css
  src/components/player/CurrentMusicList.tsx
  src/components/player/MusicPlayer.tsx
  src/components/player/Pl.tsx
  src/components/player/Player.tsx
  src/components/search/SearchForm.tsx
  src/shared/musicPlayer/api.ts
  src/shared/search/api.ts
  src/shared/store/playerStore.ts
  src/types/musicPlayer/types.ts
Labels: bug, style

#253 Style(#241,#251) : 마이페이지/유저페이지 보드 컴포넌트 ui 작업, 유저페이지 비공개 컴포넌트 ui 작업 / Dir(#252) : 마이페이지 버튼 컴포넌트 2개 공통 컴포넌트로 이동
  public/images/play.svg
  src/components/mypage/BoardItem.tsx
  src/components/mypage/FollowerList.tsx
  src/components/mypage/FollowingList.tsx
  src/components/mypage/MyInfo.tsx
  src/components/mypage/MyPlaylist.tsx
  src/components/mypage/WriteList.tsx
  src/components/personal/GenderPage.tsx
  src/components/personal/PersonalModalDetail.tsx
  src/components/personal/PersonalRecommend.tsx
  src/components/personal/PersonalSubTest.tsx
  src/components/userpage/LockContents.tsx
  src/components/userpage/UserInfo.tsx
  src/components/userpage/UserPlaylist.tsx
  src/util/ButtonPrimary.tsx
  src/util/ButtonSecondary.tsx
  tailwind.config.ts
Labels: style

#259 Style(#250) : 커뮤니티 상세 페이지 css - 조회 - 페이지 상단 띄우기
  public/images/allow-check-box.svg
  public/images/check-box.svg
  public/images/community-detail-Image/add-current-music.svg
  public/images/community-detail-Image/add-my-playlist.svg
  public/images/community-detail-Image/back-allow.svg
  src/components/Header.tsx
  src/components/common/Container.tsx
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/communityDetail/communityCss.ts
  src/components/findpassword/FindPassword.tsx
  src/components/join/AllowOpenInfo.tsx
  src/components/join/AllowUserInfo.tsx
  src/components/join/Join.tsx
  src/components/login/Login.tsx
  src/shared/join/joinApi.ts
Labels: documentation, enhancement

#261 Fix(#260) : 마이 플레이리스트 - 노래 삭제 바로 반영 안되는 문제
  src/components/mypage/LikeBoardList.tsx
  src/components/mypage/MyPlaylist.tsx
  src/components/mypage/WriteList.tsx
  src/components/player/MusicPlayer.tsx
  src/components/userpage/LikeBoardList.tsx
  src/components/userpage/UserInfo.tsx
  src/components/userpage/UserPlaylist.tsx
  src/components/userpage/WriteList.tsx
  src/shared/mypage/api.ts
Labels: bug

#267 Style(#262) : 체크박스 커스텀 / Feat(#263,#264,#265)마이페이지/유저페이지 - 페이지네이션 공통 컴포넌트로 변경, 페이징 함수 변경
  public/images/check.svg
  src/components/mypage/CheckboxItem.tsx
  src/components/mypage/LikeBoardList.tsx
  src/components/mypage/Modal.tsx
  src/components/mypage/MyInfo.tsx
  src/components/mypage/WriteList.tsx
  src/components/userpage/LikeBoardList.tsx
  src/components/userpage/UserInfo.tsx
  src/components/userpage/WriteList.tsx
  src/shared/mypage/api.ts
  src/util/ButtonSecondary.tsx
  src/util/util.ts
  tailwind.config.ts
Labels: documentation, style

#270 Style(#268) : MBTI 토글 스위치 디자인 수정
  public/images/arrow_forward_ios.svg
  public/images/double_arrow.svg
  public/images/double_arrow_left.svg
  public/images/searchIcon (2).svg
  src/components/Header.tsx
  src/components/personal/GenderPage.tsx
  src/components/personal/PersonalModal.tsx
  src/components/personal/PersonalModalDetail.tsx
  src/components/personal/PersonalRecommend.tsx
  src/components/personal/PersonalSubTest.tsx
  src/components/personal/PersonalTestResult.tsx
  src/components/personal/ResultChart.tsx
  src/components/personal/ResultPage.tsx
  src/components/search/SearchForm.tsx
Labels: bug, style

#271 Style(#249) : 커뮤니티 상세 페이지 css - 등록, 음악 검색 등록 css - 내용 배치
  public/images/community-detail-Image/search-button.svg
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/communityDetail/communityCss.ts
  src/components/login/Login.tsx
  src/components/search/ModalMusicData.tsx
  src/components/search/MusicSearch.tsx
  src/components/search/MusicSearchModal.tsx
Labels: documentation, enhancement, style

#275 Style(#274) : 커뮤니티 상세 페이지 CSS - 음악 검색 등록 시간 띄우기
  src/components/search/ModalMusicData.tsx
Labels: documentation, style

#276 Style(#266) : 플레이어 버튼 커스텀, 현재 음악 삭제 오류 수정
  public/images/musicList.svg
  public/images/musicLyricsButton.svg
  public/images/musicShuffle.svg
  public/images/musicShuffleOff.svg
  public/images/musicThumbnailDefault.svg
  public/images/myPlayListButton.svg
  src/app/(nonAuth)/search/page.tsx
  src/components/common/Container.tsx
  src/components/communityList/CommunityListSort.tsx
  src/components/player/AudioCss.css
  src/components/player/CurrentMusicList.tsx
  src/components/player/MusicPlayer.tsx
  src/components/player/Player.tsx
  src/components/player/playerIcons/MyLoopIcon.tsx
  src/components/player/playerIcons/MyLoopOffIcon.tsx
  src/components/player/playerIcons/MyNextIcon.tsx
  src/components/player/playerIcons/MyPauseIcon.tsx
  src/components/player/playerIcons/MyPreviousIcon.tsx
  src/components/search/NoSearchResultItem.tsx
  src/components/search/SearchedMusicData.tsx
Labels: bug, style

#280 Fix(#279) : 자신의 유저 프로필 페이지 접속 못하도록 로직 추가
  src/components/userpage/UserInfo.tsx
Labels: bug

#283 Fix(#281,#282) : 커뮤니티 상세 페이지 UI 피드백 반영 (feat. 디자이너님) 및 상세 페이지 조회, 등록 글자 간격 및 폰트 크기, 폰트 진하기 수정, 본인 유저페이지 진입 방지
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/LikeButton.tsx
  src/components/join/Join.tsx
  src/components/search/ModalMusicData.tsx
Labels: bug, documentation, enhancement

#289 Style(#284,#285,#288) : 메인, 마이페이지/유저 페이지 ui 수정 / Feat(#286,#287) : 마이플리/유저플리 한개이상 선택 시 버튼 나오도록 작업
  public/images/next.svg
  public/images/prev.svg
  src/components/main/GenreMusicItem.tsx
  src/components/main/TopLikedBoard.tsx
  src/components/mypage/BoardItem.tsx
  src/components/mypage/FollowerList.tsx
  src/components/mypage/FollowingList.tsx
  src/components/mypage/MyInfo.tsx
  src/components/mypage/MyPlaylist.tsx
  src/components/userpage/UserPlaylist.tsx
  src/shared/mypage/api.ts
Labels: documentation, style

#293 Style(#291) : 인기게시글 없을 때 노출될 ui 작업
  src/components/main/TopLikedBoard.tsx
Labels: style

#292 Fix(#290) : 현재 재생 목록이 없을 경우 음악 추가 오류 해결 / Style : 헤더,푸터, 댓글 UI 수정Style/personal
  public/images/Rectangle 156.svg
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/comment/CommentForm.tsx
  src/components/comment/CommentsList.tsx
  src/components/comments/CommentForm.tsx
  src/components/comments/CommentsList.tsx
  src/components/personal/GenderPage.tsx
  src/components/personal/PersonalRecommend.tsx
  src/components/personal/PersonalSubTest.tsx
  src/components/search/SearchForm.tsx
  src/shared/personal/personalApi.ts
Labels: bug, style

#304 Fix(#302) : 두 번클릭해야 토글 이동 버그 해결
  src/components/comment/CommentsList.tsx
  src/components/personal/PersonalRecommend.tsx
  src/components/personal/PersonalSubTest.tsx
  src/components/personal/ResultChart.tsx
Labels: bug

#307 Feat(#301, #306) : 좋아요수/댓글수 표시 및 플레이리스트 토글 기능 추가
  public/images/chevron-down.svg
  src/components/mypage/BoardItem.tsx
  src/components/mypage/MyPlaylist.tsx
  src/components/userpage/UserPlaylist.tsx
Labels: documentation

#310 Fix(#305) 플레이리스트 가사 수정, 댓글, 좋아요 99 수정
  src/app/(nonAuth)/community/page.tsx
  src/app/(nonAuth)/search/page.tsx
  src/components/communityList/CommunityListData.tsx
  src/components/communityList/CommunityListSort.tsx
  src/components/player/CurrentMusicList.tsx
  src/components/player/MusicPlayer.tsx
  src/components/player/Player.tsx
  src/components/player/playerIcons/MyLoopIcon.tsx
  src/components/player/playerIcons/MyLoopOffIcon.tsx
  src/components/search/GenreMusicRecommendations.tsx
  src/components/search/GenreRandomMusic.tsx
  src/components/search/MusicSearchModal.tsx
  src/components/search/SearchedCommunityData.tsx
  src/shared/musicPlayer/api.ts
  src/shared/search/api.ts
  src/types/musicPlayer/types.ts
  src/util/util.ts
Labels: bug

#312 style,Fix(#311) : 커뮤니티 상세 페이지 - 댓글, 좋아요 99이상 숫자 표시와 +플러스 표시, 그 외에 등록, 수정 페이지 에러 해결
  src/app/(nonAuth)/community/[id]/page.tsx
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/communityDetail/LikeButton.tsx
  src/components/communityDetail/communityDetailRead.tsx
  src/components/join/Join.tsx
  src/components/logout/LogOutButton.tsx
  src/components/search/MusicSearch.tsx
  src/components/search/MusicSearchModal.tsx
  src/query/communityDetail/queryKey.ts
  src/shared/communitydetail/detailApi.ts
  src/shared/store/communityDetailStore.ts
  src/types/communityDetail/detailTypes.ts
Labels: bug, documentation, enhancement, style

#317 Fix (#316) : 로그인 - 회원가입 유효성 추가
  src/components/join/Join.tsx
Labels: bug, documentation, enhancement

#324 Feat(#321) : 슬라이드 배너 링크 기능 추가 / Style(#322) : 음악 추천 디자인 수정
  src/components/main/GenreMusicItem.tsx
  src/components/main/MainBanner.tsx
Labels: documentation, enhancement, style

#325 Fix(#232) : 로그인 - 소셜로그인 잠시 제거
  src/components/communityDetail/CommunityContents.tsx
  src/components/login/Login.tsx
Labels: documentation

#328 Style(#327) : 배포 서버와 로컬 서버의 css 우선순위 다른 문제
  src/components/main/GenreMusicItem.tsx
Labels: style

#332 Style(#331) : 퍼스널 진단 페이지 UI 마무리 작업 중
  public/images/Frame 669.svg
  src/components/Header.tsx
  src/components/comment/CommentForm.tsx
  src/components/comment/CommentsList.tsx
  src/components/logout/LogOutButton.tsx
  src/components/personal/GenderPage.tsx
  src/components/personal/PersonalModalDetail.tsx
  src/components/personal/PersonalRecommend.tsx
  src/components/personal/PersonalSubTest.tsx
  src/components/personal/PersonalTestResult.tsx
  src/components/search/SearchForm.tsx
Labels: style

#337 Feat : 마이페이지 닉네임 글자수 10자로 제한, 유저별 프로필 페이지 쿼리키 동적으로 부여
  src/components/mypage/MyInfo.tsx
  src/components/userpage/UserInfo.tsx
Labels: documentation, enhancement

#343 Style : alert창 라이브러리 임시사용 / Feat(#340) : 댓글목록에서도 유저 프로필이미지 이동 추가
  package.json
  src/components/comment/CommentForm.tsx
  src/components/comment/CommentsList.tsx
  src/components/personal/GenderPage.tsx
  src/shared/musicPlayer/api.ts
  yarn.lock
Labels: documentation, enhancement, style

#345 Script/sweet alert 적용
  src/components/communityList/CommunityListData.tsx
  src/components/player/MusicPlayer.tsx
  src/components/search/NoSearchResultItem.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchedMusicData.tsx
  src/shared/musicPlayer/api.ts
Labels: enhancement

#347 Feat(#344, #346) : SweetAlert2 적용 및 유저 기본 썸네일 적용
  src/components/main/GenreMusicItem.tsx
  src/components/main/TopLikedBoard.tsx
  src/components/mypage/BoardItem.tsx
  src/components/mypage/LikeBoardList.tsx
  src/components/mypage/MyInfo.tsx
  src/components/mypage/MyPlaylist.tsx
  src/components/mypage/WriteList.tsx
  src/components/userpage/LikeBoardList.tsx
  src/components/userpage/UserPlaylist.tsx
  src/components/userpage/WriteList.tsx
Labels: documentation, enhancement

#349 Fix(#341, #342, #348) : (UT 피드백 반영-8번째 유저 피드백) 커뮤니티 등록 페이지 - 음악 검색 등록 문제 해결
  public/images/loadingBar.gif
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/search/MusicSearch.tsx
  src/components/search/MusicSearchModal.tsx
Labels: bug, documentation, enhancement

#352 Release : release v0.0.1
  package.json
  public/images/loadingBar.gif
  public/images/playerBar.svg
  public/images/userDefaultImg.svg
  src/components/comment/CommentForm.tsx
  src/components/comment/CommentsList.tsx
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/communityList/CommunityListData.tsx
  src/components/main/GenreMusicItem.tsx
  src/components/main/TopLikedBoard.tsx
  src/components/mypage/BoardItem.tsx
  src/components/mypage/LikeBoardList.tsx
  src/components/mypage/MyInfo.tsx
  src/components/mypage/MyPlaylist.tsx
  src/components/mypage/WriteList.tsx
  src/components/personal/GenderPage.tsx
  src/components/player/AudioCss.css
  src/components/player/MusicPlayer.tsx
  src/components/search/MusicSearch.tsx
  src/components/search/MusicSearchModal.tsx
  src/components/search/NoSearchResultItem.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchedCommunityData.tsx
  src/components/search/SearchedMusicData.tsx
  src/components/userpage/LikeBoardList.tsx
  src/components/userpage/UserPlaylist.tsx
  src/components/userpage/WriteList.tsx
  src/query/musicPlayer/musicPlayerQueryKey.ts
  src/shared/musicPlayer/api.ts
  yarn.lock
Labels: release

#353 Style:커뮤니티 이미지 사이즈 조정
  public/images/playerBar.svg
  src/components/communityList/CommunityListData.tsx
  src/components/player/AudioCss.css
  src/components/player/MusicPlayer.tsx
  src/components/player/Player.tsx
  src/components/search/SearchedCommunityData.tsx
  src/components/search/SearchedMusicData.tsx
Labels: style

#363 Fix(#323,#354,#360,#361): 16번째, 18번째, 25번째 UT 피드백 반영
  public/images/brand-logo/logo.png
  src/app/api/auth/[...nextauth]/route.ts
  src/components/findpassword/FindPassword.tsx
  src/components/join/Join.tsx
  src/components/join/value.ts
  src/components/login/Login.tsx
  src/shared/join/joinApi.ts
  src/shared/login/loginApi.ts
Labels: bug, documentation, enhancement

#364 Fix(#323,#354,#360,#361): 로그인, 회원가입 - 16번째, 18번째, 25번째 피드백 반영
  public/images/brand-logo/logo.png
  src/app/api/auth/[...nextauth]/route.ts
  src/components/findpassword/FindPassword.tsx
  src/components/join/Join.tsx
  src/components/join/value.ts
  src/components/login/Login.tsx
  src/shared/join/joinApi.ts
  src/shared/login/loginApi.ts
Labels: bug, documentation, enhancement, style
